services:
  ros2-dev-iron:
    build:
      context: ./
      dockerfile: ./Dockerfile

    # image: osrf/ros:iron-desktop
      args:
          USERNAME: ${USERNAME}
          USER_UID: ${USER_UID}
          USER_GID: ${USER_GID}

    environment:
      - USERNAME=${USERNAME}

    container_name: ros2-iron-simple-node
    network_mode: host
    ipc: host
    volumes:
      - ../app:/ws # Replace with your host and container paths
      - ${INPUT_PATH}:/input
      # - ${OUTPUT_DIR}:/output
    stdin_open: true
    tty: true
    # command: ["/ws/scripts/start_script.sh"]
